FROM debian:bullseye
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update\
    && apt-get install -y wget curl\
    && echo "deb http://www.deb-multimedia.org bullseye main non-free" >> /etc/apt/sources.list\
    && wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb\
    && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb\
    && rm -rf deb-multimedia-keyring_2016.8.1_all.deb\
    && apt-get update\
    && apt-get install -y python python3 python3-pip git unzip vim\
    && apt-get install -y autoconf cargo git libfftw3-dev libtool vapoursynth-dev nasm\
    && apt-get clean\
    && apt-get autoremove \
    && pip3 install meson ninja

ENV PYTHONPATH "${PYTHONPATH}:/python_module"
