FROM debian:bullseye
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update\
    && apt-get install -y wget curl\
    && echo "deb http://www.deb-multimedia.org bullseye main non-free" >> /etc/apt/sources.list\
    && apt-get update -oAcquire::AllowInsecureRepositories=true\
    && apt-get install -y deb-multimedia-keyring\
    && apt-get update\
    && apt-get install -y python python3 python3-pip git unzip vim\
    && apt-get install -y autoconf cargo git libfftw3-dev libtool vapoursynth-dev \
    && apt-get clean\
    && apt-get autoremove \
    && pip3 install meson ninja

ENV PYTHONPATH "${PYTHONPATH}:/python_module"
