version: "2.1"
services:
    vapoursynth-yuuno:
        image: encodeguy/vapoursynth-linux:v0
        container_name: encode
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./function:/python_module
            - ./scripts:/scripts
            - /root/source:/encode
        ports:
            - 8888:8888
        restart: unless-stopped
        tty: true
        entrypoint: ["./jupyter.sh"]
        working_dir: /scripts
